   name: Notify Telegram

   on: [push]

   jobs:
     notify:
       runs-on: ubuntu-latest
       steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Send message to Telegram
         env:
           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="New commit in the repository!"
   
